package projectEuler;

/**
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * <blockquote> 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... </blockquote>
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 */
public class Problem2 {

	public static void main(String[] args) {
		
		int sum = 0;
		
		int num1 = 1;
		int num2 = 1;
		int num3 = 0;
		
		while (num1 < 4000000 && num2 < 4000000) {
			
			if (num1 % 2 == 0) {
				
				sum += num1;
				
			}
			
			num3 = num2;
			num2 = num1;
			
			num1 = num2 + num3;
			
		}
		
		System.out.println(sum);

	}

}
